module.exports = {
  packages: [
    "getting-started",
    "onboardings",
    "carousels",
    "parallaxes",
    "dropdowns",
    "headers",
    "lists",
    "arcsliders",
    "sliders",
    "tabbars",
    "bottomsheets",
    "loaders",
    "circular-progress-bars",
    "charts",
    "buttons",
    "accordions",
    "miscellaneous",
    "fullapps",
  ],
};
